# Generated by Django 4.2.7 on 2023-11-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_appealing_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appealing',
            options={'verbose_name': 'Appealing', 'verbose_name_plural': 'Appealings'},
        ),
    ]
