# Generated by Django 4.2.7 on 2023-11-20 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Haqqimizda', 'verbose_name_plural': 'Haqqimizda'},
        ),
    ]
